### PR TITLE
Add Javascript array example

### PR DESCRIPTION
**Pull request by bitflower**

### CODE REVIEW

**Comment by bitflower** [comment]
As discussed on Discord: Will test this first, then come back to see if the code is 100% correct.

**Review by domoritz — CHANGES_REQUESTED** [review]
I don't think this is the best approach. It's more efficient to instead create an arrow table from the array and then inserting the arrow table.

**Comment by bitflower** [comment]
Are you referring to `apache-arrow` @domoritz ? Because this would introduce another dependency just for reading a vanilla array.

**Comment by domoritz** [comment]
Arrow is already a dependency of duckdb wasm.

**Comment by bitflower** [comment]
Cool, didn't know @domoritz 

Will come back with adjustments

**Comment by Alex-Monahan** [comment]
Mind if we show both examples? I've seen cases where inserting as JSON worked, but converting to Arrow ahead of time failed (due to mismatched types within a column like 2 and '2')

**Review by Mytherin — APPROVED** [review]

**Pull request merged**
