### PR TITLE
Bump DuckDB, properly propagate wasm_* platform and add test

### PR DESCRIPTION
**Pull request by carlopi**
Previously the custom provided platform was not propagated in the right place, fixed and added a test.

Fixes https://github.com/duckdb/duckdb-wasm/issues/1298

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Are all the `console.log` messages left in intentionally?

**Comment by carlopi** [comment]
Yes, it's not great practice, but currently strategy of shallowing exceptions is not great since shallows both DuckDB-side exceptions (like failures) and JS exceptions (these might be harmless, and might make sense to skip in some cases).

To users not opening the console, it should give roughly the same experience, but upon inspection some information of what went wrong is available.
Unsure whether to consider this a blocker to tag a version or not, but we can check tomorrow.

Note that exceptions are still used only for exceptional behaviour, so I would assume (but I am not completely sure) that the number of exceptions will be low (bounded by the number of failed queries ?).

**Comment by Mytherin** [comment]
Alright, makes sense to me. Thanks

**Comment by whscullin** [comment]
Hi, just came across this when diagnosing log spamming during some of our tests. It would be nice to be able to disable the currently unconditional `console.log` so we can have clean test outputs. Working around this mocking `console.log` for now.

**Comment by whscullin** [comment]
I guess it's unclear to me why this isn't just using the `Logger` interface, at least in the worker where it's available. that seems like it would allow for configuration. I can do a PR for that if that seems reasonable.

**Comment by carlopi** [comment]
I moved this to an independent issue, #1518.

Why this happened is an oversight on my side, there was a comment like:
```cpp
                    // Next few lines should argubly in separate JavaScript-land function call
                    // TODO: move them out / have them configurable
```
that I never got to address.

Fix is trivial, only problem is that this is in DuckDB codebase and will require patching while building duckdb in duckdb-wasm, but there is already infrastructure for that.

**Pull request merged**
